### ISSUE TITLE
Folder Template

### ISSUE THREAD

**Issue by StepanSwhite** [Sorrow446/SberZvuk-Downloader#2]
add the ability to change albumFolder, please. 
right now there is not enough year in the folder name. 
"albumArtist" - "album" **("year")**

and for personal cataloging: how can i add "[catalogNumber]" (not meta) to the beginning of each folder name? 
[catalogNumber] albumArtist - album (year)

**Comment by Sorrow446** [comment]
Will be implemented into the next update, but the album folder template won't be able to support track-unique variables like `title` as it needs to be generated before any of the tracks. Available variables would be: `album`, `albumArtist` and `year`.

What do you mean by catalogue number? I assume you mean the album ID at the end of the URLs.

**Comment by Sorrow446** [comment]
I could make a special build just for you as this is a niche request.

Unfortunately SberZvuk don't provide UPCs, so it'd be hard to find the matching catalogue number.
This is all the album metadata they have:
```go
type Release struct {
	ArtistIds []int  `json:"artist_ids"`
	Template  string `json:"template"`
	Title     string `json:"title"`
	Image     struct {
		Src           string `json:"src"`
		Palette       string `json:"palette"`
		PaletteBottom string `json:"palette_bottom"`
	} `json:"image"`
	SearchTitle   string   `json:"search_title"`
	Explicit      bool     `json:"explicit"`
	SearchCredits string   `json:"search_credits"`
	TrackIds      []int    `json:"track_ids"`
	ArtistNames   []string `json:"artist_names"`
	Credits       string   `json:"credits"`
	LabelID       int      `json:"label_id"`
	Availability  int      `json:"availability"`
	HasImage      bool     `json:"has_image"`
	Date          int      `json:"date"`
	Price         int      `json:"price"`
	Type          string   `json:"type"`
	ID            int      `json:"id"`
	GenreIds      []int    `json:"genre_ids"`
}
```
Is there some other reliable way we can match catalogue IDs?

**Comment by Sorrow446** [comment]
Album templates are now implemented. 

You can use this template to include the year in brackets.
`{{.albumArtist}} - {{.album}} ({{.year}})`
