### ISSUE TITLE
download bugs

### ISSUE THREAD

**Issue by GeneTamlin** [Sorrow446/SberZvuk-Downloader#5]
After i downloaded the album, i noticed that one song didn't sound right. I'll just upload the file, the composition seems to play with little gaps. I don't know how to explain, you'd better just listen. It's very frustrating and I have no idea what caused it. I have already downloaded a couple of dozen albums in a flac and I hope that this will not happen again :^(
On the site and in the Sberzvuk app, the composition sounds normal... I tried downloading the album again but nothing changed. The composition starts to be laggy around 2:13.
[03. On The Run (2011 Remastered Version).zip](https://github.com/Sorrow446/SberZvuk-Downloader/files/8457681/03.On.The.Run.2011.Remastered.Version.zip)
.

**Comment by Sorrow446** [comment]
Track is hosted on Sber's servers broken, but their players correct it. Bad duration, FFmpeg reports "sample/frame number mismatch". Gonna close this issue as it's not a problem with the tool.
