### ISSUE TITLE
Dots in folder name

### ISSUE THREAD

**Issue by lexxxxion** [Sorrow446/SberZvuk-Downloader#6]
On Windows, is there is an ellipsis (three dots) in the album name, it is omitted when the folder is created. Then the script fails to locate it.

**Comment by Sorrow446** [comment]
… is an allowed character in Windows file and folder names. Could you link the album?

**Comment by lexxxxion** [comment]
Sorry, it turns out, those are three separate dots, not ellipsis. But the problem still exists, dots can be used in file names, but not folder names. Windows omits them automatically, but the app tries to address the folder, as if the dots were still there.

**Comment by Sorrow446** [comment]
Yeah, filenames and folders can't end with periods in Windows. strings.TrimSuffix would do the job. Will implement soon.

**Comment by Sorrow446** [comment]
Fix implemented.
