### ISSUE TITLE
Feature request: add auth by token (bypass login with emai|pass)

### ISSUE THREAD

**Issue by tst32** [Sorrow446/SberZvuk-Downloader#7]
if we have an  of auth token (provided for a non anonymous user 33 chars from https://zvuk.com/api/v2/tiny/profile). it would be useful not to login but proceed directly to all other operations

expected ./main --token <33 secret chars> URLS

it could be done with config.json as well

```JSON
{
    "email": "",
    "password": "",
    "format": 3,
    "outPath": "Zvuk downloads",
    "albumTemplate": "{{.albumArtist}} - {{.album}}",
    "trackTemplate": "{{.trackPad}}. {{.title}}",
    "maxCover": true,
    "lyrics": true,
    "speedLimit": -1,
    "keepCover": true
    "token": 6SJPyDCub8EJtXQuRPyu5q2meJKW8yleb
}
```
example token from /dev/urandom

**Comment by Sorrow446** [comment]
I don't see the point in this. Could you explain the benefit of using a token over credentials?

**Comment by tst32** [comment]
In my case, I have a token in my profile, email, but no password. This happens because of the way of authorization in openplay - I'm authorized through a third-party service. accordingly, I can not specify the password. In the course of the program operation the password is used only together with the email to get the token. I'm sorry if I missed something, because I was just looking through the code quickly. 
cheers!

**Comment by Sorrow446** [comment]
That makes perfect sense, thanks. This token should be identical to the one the auth function returns, I'll need to check that.

**Comment by Sorrow446** [comment]
Implemented. https://github.com/Sorrow446/SberZvuk-Downloader/commit/de1d87d2dcb50ff736bc4200e4cdaca6b3f77657
Let me know if you need binaries.

**Comment by tst32** [comment]
Yes, mine is also 32 length! 
it works, as follow 
```
./main  https://zvuk.com/track/57571043

 _____         _      ____                _           _         
|__   |_ _ _ _| |_   |    \ ___ _ _ _ ___| |___ ___ _| |___ ___ 
|   __| | | | | '_|  |  |  | . | | | |   | | . | .'| . | -_|  _|
|_____|\_/|___|_,_|  |____/|___|_____|_|_|_|___|__,|___|___|_|
   
Signed in successfully - <skipped>.3months

Album 1 of 1:
Invalid URL: https://zvuk.com/track/57571043
```
so i'm happy token auth works, but something is wrong with request

**Comment by Sorrow446** [comment]
Album links only, sorry.

**Comment by tst32** [comment]
![image](https://user-images.githubusercontent.com/23115742/166316668-1620e12c-2e06-49fb-a545-293fe5aebb32.png)
Oh, nice! thanks you so much! 🛩️
